// Code generated by go-swagger; DO NOT EDIT.

package smtp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteSMTPTemplateParams creates a new DeleteSMTPTemplateParams object
// with the default values initialized.
func NewDeleteSMTPTemplateParams() *DeleteSMTPTemplateParams {
	var ()
	return &DeleteSMTPTemplateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteSMTPTemplateParamsWithTimeout creates a new DeleteSMTPTemplateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteSMTPTemplateParamsWithTimeout(timeout time.Duration) *DeleteSMTPTemplateParams {
	var ()
	return &DeleteSMTPTemplateParams{

		timeout: timeout,
	}
}

// NewDeleteSMTPTemplateParamsWithContext creates a new DeleteSMTPTemplateParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteSMTPTemplateParamsWithContext(ctx context.Context) *DeleteSMTPTemplateParams {
	var ()
	return &DeleteSMTPTemplateParams{

		Context: ctx,
	}
}

// NewDeleteSMTPTemplateParamsWithHTTPClient creates a new DeleteSMTPTemplateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteSMTPTemplateParamsWithHTTPClient(client *http.Client) *DeleteSMTPTemplateParams {
	var ()
	return &DeleteSMTPTemplateParams{
		HTTPClient: client,
	}
}

/*DeleteSMTPTemplateParams contains all the parameters to send to the API endpoint
for the delete Smtp template operation typically these are written to a http.Request
*/
type DeleteSMTPTemplateParams struct {

	/*TemplateID
	  id of the template

	*/
	TemplateID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete Smtp template params
func (o *DeleteSMTPTemplateParams) WithTimeout(timeout time.Duration) *DeleteSMTPTemplateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete Smtp template params
func (o *DeleteSMTPTemplateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete Smtp template params
func (o *DeleteSMTPTemplateParams) WithContext(ctx context.Context) *DeleteSMTPTemplateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete Smtp template params
func (o *DeleteSMTPTemplateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete Smtp template params
func (o *DeleteSMTPTemplateParams) WithHTTPClient(client *http.Client) *DeleteSMTPTemplateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete Smtp template params
func (o *DeleteSMTPTemplateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTemplateID adds the templateID to the delete Smtp template params
func (o *DeleteSMTPTemplateParams) WithTemplateID(templateID int64) *DeleteSMTPTemplateParams {
	o.SetTemplateID(templateID)
	return o
}

// SetTemplateID adds the templateId to the delete Smtp template params
func (o *DeleteSMTPTemplateParams) SetTemplateID(templateID int64) {
	o.TemplateID = templateID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteSMTPTemplateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param templateId
	if err := r.SetPathParam("templateId", swag.FormatInt64(o.TemplateID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
