// Code generated by go-swagger; DO NOT EDIT.

package smtp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteSMTPBlockedContactsEmailParams creates a new DeleteSMTPBlockedContactsEmailParams object
// with the default values initialized.
func NewDeleteSMTPBlockedContactsEmailParams() *DeleteSMTPBlockedContactsEmailParams {
	var ()
	return &DeleteSMTPBlockedContactsEmailParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteSMTPBlockedContactsEmailParamsWithTimeout creates a new DeleteSMTPBlockedContactsEmailParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteSMTPBlockedContactsEmailParamsWithTimeout(timeout time.Duration) *DeleteSMTPBlockedContactsEmailParams {
	var ()
	return &DeleteSMTPBlockedContactsEmailParams{

		timeout: timeout,
	}
}

// NewDeleteSMTPBlockedContactsEmailParamsWithContext creates a new DeleteSMTPBlockedContactsEmailParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteSMTPBlockedContactsEmailParamsWithContext(ctx context.Context) *DeleteSMTPBlockedContactsEmailParams {
	var ()
	return &DeleteSMTPBlockedContactsEmailParams{

		Context: ctx,
	}
}

// NewDeleteSMTPBlockedContactsEmailParamsWithHTTPClient creates a new DeleteSMTPBlockedContactsEmailParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteSMTPBlockedContactsEmailParamsWithHTTPClient(client *http.Client) *DeleteSMTPBlockedContactsEmailParams {
	var ()
	return &DeleteSMTPBlockedContactsEmailParams{
		HTTPClient: client,
	}
}

/*DeleteSMTPBlockedContactsEmailParams contains all the parameters to send to the API endpoint
for the delete SMTP blocked contacts email operation typically these are written to a http.Request
*/
type DeleteSMTPBlockedContactsEmailParams struct {

	/*Email
	  contact email (urlencoded) to unblock.

	*/
	Email string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete SMTP blocked contacts email params
func (o *DeleteSMTPBlockedContactsEmailParams) WithTimeout(timeout time.Duration) *DeleteSMTPBlockedContactsEmailParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete SMTP blocked contacts email params
func (o *DeleteSMTPBlockedContactsEmailParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete SMTP blocked contacts email params
func (o *DeleteSMTPBlockedContactsEmailParams) WithContext(ctx context.Context) *DeleteSMTPBlockedContactsEmailParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete SMTP blocked contacts email params
func (o *DeleteSMTPBlockedContactsEmailParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete SMTP blocked contacts email params
func (o *DeleteSMTPBlockedContactsEmailParams) WithHTTPClient(client *http.Client) *DeleteSMTPBlockedContactsEmailParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete SMTP blocked contacts email params
func (o *DeleteSMTPBlockedContactsEmailParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEmail adds the email to the delete SMTP blocked contacts email params
func (o *DeleteSMTPBlockedContactsEmailParams) WithEmail(email string) *DeleteSMTPBlockedContactsEmailParams {
	o.SetEmail(email)
	return o
}

// SetEmail adds the email to the delete SMTP blocked contacts email params
func (o *DeleteSMTPBlockedContactsEmailParams) SetEmail(email string) {
	o.Email = email
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteSMTPBlockedContactsEmailParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param email
	if err := r.SetPathParam("email", o.Email); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
