// Code generated by go-swagger; DO NOT EDIT.

package contacts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"APIv3_go_wrapper/models"
)

// NewUpdateAttributeParams creates a new UpdateAttributeParams object
// with the default values initialized.
func NewUpdateAttributeParams() *UpdateAttributeParams {
	var ()
	return &UpdateAttributeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateAttributeParamsWithTimeout creates a new UpdateAttributeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateAttributeParamsWithTimeout(timeout time.Duration) *UpdateAttributeParams {
	var ()
	return &UpdateAttributeParams{

		timeout: timeout,
	}
}

// NewUpdateAttributeParamsWithContext creates a new UpdateAttributeParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateAttributeParamsWithContext(ctx context.Context) *UpdateAttributeParams {
	var ()
	return &UpdateAttributeParams{

		Context: ctx,
	}
}

// NewUpdateAttributeParamsWithHTTPClient creates a new UpdateAttributeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateAttributeParamsWithHTTPClient(client *http.Client) *UpdateAttributeParams {
	var ()
	return &UpdateAttributeParams{
		HTTPClient: client,
	}
}

/*UpdateAttributeParams contains all the parameters to send to the API endpoint
for the update attribute operation typically these are written to a http.Request
*/
type UpdateAttributeParams struct {

	/*AttributeCategory
	  Category of the attribute

	*/
	AttributeCategory string
	/*AttributeName
	  Name of the existing attribute

	*/
	AttributeName string
	/*UpdateAttribute
	  Values to update an attribute

	*/
	UpdateAttribute *models.UpdateAttribute

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update attribute params
func (o *UpdateAttributeParams) WithTimeout(timeout time.Duration) *UpdateAttributeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update attribute params
func (o *UpdateAttributeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update attribute params
func (o *UpdateAttributeParams) WithContext(ctx context.Context) *UpdateAttributeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update attribute params
func (o *UpdateAttributeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update attribute params
func (o *UpdateAttributeParams) WithHTTPClient(client *http.Client) *UpdateAttributeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update attribute params
func (o *UpdateAttributeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAttributeCategory adds the attributeCategory to the update attribute params
func (o *UpdateAttributeParams) WithAttributeCategory(attributeCategory string) *UpdateAttributeParams {
	o.SetAttributeCategory(attributeCategory)
	return o
}

// SetAttributeCategory adds the attributeCategory to the update attribute params
func (o *UpdateAttributeParams) SetAttributeCategory(attributeCategory string) {
	o.AttributeCategory = attributeCategory
}

// WithAttributeName adds the attributeName to the update attribute params
func (o *UpdateAttributeParams) WithAttributeName(attributeName string) *UpdateAttributeParams {
	o.SetAttributeName(attributeName)
	return o
}

// SetAttributeName adds the attributeName to the update attribute params
func (o *UpdateAttributeParams) SetAttributeName(attributeName string) {
	o.AttributeName = attributeName
}

// WithUpdateAttribute adds the updateAttribute to the update attribute params
func (o *UpdateAttributeParams) WithUpdateAttribute(updateAttribute *models.UpdateAttribute) *UpdateAttributeParams {
	o.SetUpdateAttribute(updateAttribute)
	return o
}

// SetUpdateAttribute adds the updateAttribute to the update attribute params
func (o *UpdateAttributeParams) SetUpdateAttribute(updateAttribute *models.UpdateAttribute) {
	o.UpdateAttribute = updateAttribute
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateAttributeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param attributeCategory
	if err := r.SetPathParam("attributeCategory", o.AttributeCategory); err != nil {
		return err
	}

	// path param attributeName
	if err := r.SetPathParam("attributeName", o.AttributeName); err != nil {
		return err
	}

	if o.UpdateAttribute != nil {
		if err := r.SetBodyParam(o.UpdateAttribute); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
