// Code generated by go-swagger; DO NOT EDIT.

package email_campaigns

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/sendinblue/APIv3-go-library/models"
)

// DeleteEmailCampaignReader is a Reader for the DeleteEmailCampaign structure.
type DeleteEmailCampaignReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteEmailCampaignReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteEmailCampaignNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteEmailCampaignBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteEmailCampaignNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteEmailCampaignNoContent creates a DeleteEmailCampaignNoContent with default headers values
func NewDeleteEmailCampaignNoContent() *DeleteEmailCampaignNoContent {
	return &DeleteEmailCampaignNoContent{}
}

/*DeleteEmailCampaignNoContent handles this case with default header values.

Email campaign has been deleted
*/
type DeleteEmailCampaignNoContent struct {
}

func (o *DeleteEmailCampaignNoContent) Error() string {
	return fmt.Sprintf("[DELETE /emailCampaigns/{campaignId}][%d] deleteEmailCampaignNoContent ", 204)
}

func (o *DeleteEmailCampaignNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteEmailCampaignBadRequest creates a DeleteEmailCampaignBadRequest with default headers values
func NewDeleteEmailCampaignBadRequest() *DeleteEmailCampaignBadRequest {
	return &DeleteEmailCampaignBadRequest{}
}

/*DeleteEmailCampaignBadRequest handles this case with default header values.

bad request
*/
type DeleteEmailCampaignBadRequest struct {
	Payload *models.ErrorModel
}

func (o *DeleteEmailCampaignBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /emailCampaigns/{campaignId}][%d] deleteEmailCampaignBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteEmailCampaignBadRequest) GetPayload() *models.ErrorModel {
	return o.Payload
}

func (o *DeleteEmailCampaignBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteEmailCampaignNotFound creates a DeleteEmailCampaignNotFound with default headers values
func NewDeleteEmailCampaignNotFound() *DeleteEmailCampaignNotFound {
	return &DeleteEmailCampaignNotFound{}
}

/*DeleteEmailCampaignNotFound handles this case with default header values.

Campaign ID not found
*/
type DeleteEmailCampaignNotFound struct {
	Payload *models.ErrorModel
}

func (o *DeleteEmailCampaignNotFound) Error() string {
	return fmt.Sprintf("[DELETE /emailCampaigns/{campaignId}][%d] deleteEmailCampaignNotFound  %+v", 404, o.Payload)
}

func (o *DeleteEmailCampaignNotFound) GetPayload() *models.ErrorModel {
	return o.Payload
}

func (o *DeleteEmailCampaignNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
