// Code generated by go-swagger; DO NOT EDIT.

package email_campaigns

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/sendinblue/APIv3-go-library/models"
)

// UpdateEmailCampaignsReader is a Reader for the UpdateEmailCampaigns structure.
type UpdateEmailCampaignsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateEmailCampaignsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewUpdateEmailCampaignsNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewUpdateEmailCampaignsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewUpdateEmailCampaignsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateEmailCampaignsNoContent creates a UpdateEmailCampaignsNoContent with default headers values
func NewUpdateEmailCampaignsNoContent() *UpdateEmailCampaignsNoContent {
	return &UpdateEmailCampaignsNoContent{}
}

/*UpdateEmailCampaignsNoContent handles this case with default header values.

Email Campaign has been updated
*/
type UpdateEmailCampaignsNoContent struct {
}

func (o *UpdateEmailCampaignsNoContent) Error() string {
	return fmt.Sprintf("[PUT /emailCampaigns/{campaignId}][%d] updateEmailCampaignsNoContent ", 204)
}

func (o *UpdateEmailCampaignsNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateEmailCampaignsBadRequest creates a UpdateEmailCampaignsBadRequest with default headers values
func NewUpdateEmailCampaignsBadRequest() *UpdateEmailCampaignsBadRequest {
	return &UpdateEmailCampaignsBadRequest{}
}

/*UpdateEmailCampaignsBadRequest handles this case with default header values.

bad request
*/
type UpdateEmailCampaignsBadRequest struct {
	Payload *models.ErrorModel
}

func (o *UpdateEmailCampaignsBadRequest) Error() string {
	return fmt.Sprintf("[PUT /emailCampaigns/{campaignId}][%d] updateEmailCampaignsBadRequest  %+v", 400, o.Payload)
}

func (o *UpdateEmailCampaignsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateEmailCampaignsNotFound creates a UpdateEmailCampaignsNotFound with default headers values
func NewUpdateEmailCampaignsNotFound() *UpdateEmailCampaignsNotFound {
	return &UpdateEmailCampaignsNotFound{}
}

/*UpdateEmailCampaignsNotFound handles this case with default header values.

Campaign ID not found
*/
type UpdateEmailCampaignsNotFound struct {
	Payload *models.ErrorModel
}

func (o *UpdateEmailCampaignsNotFound) Error() string {
	return fmt.Sprintf("[PUT /emailCampaigns/{campaignId}][%d] updateEmailCampaignsNotFound  %+v", 404, o.Payload)
}

func (o *UpdateEmailCampaignsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
