// Code generated by go-swagger; DO NOT EDIT.

package reseller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/sendinblue/APIv3-go-library/models"
)

// NewAddCreditsParams creates a new AddCreditsParams object
// with the default values initialized.
func NewAddCreditsParams() *AddCreditsParams {
	var ()
	return &AddCreditsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAddCreditsParamsWithTimeout creates a new AddCreditsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddCreditsParamsWithTimeout(timeout time.Duration) *AddCreditsParams {
	var ()
	return &AddCreditsParams{

		timeout: timeout,
	}
}

// NewAddCreditsParamsWithContext creates a new AddCreditsParams object
// with the default values initialized, and the ability to set a context for a request
func NewAddCreditsParamsWithContext(ctx context.Context) *AddCreditsParams {
	var ()
	return &AddCreditsParams{

		Context: ctx,
	}
}

// NewAddCreditsParamsWithHTTPClient creates a new AddCreditsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAddCreditsParamsWithHTTPClient(client *http.Client) *AddCreditsParams {
	var ()
	return &AddCreditsParams{
		HTTPClient: client,
	}
}

/*AddCreditsParams contains all the parameters to send to the API endpoint
for the add credits operation typically these are written to a http.Request
*/
type AddCreditsParams struct {

	/*AddCredits
	  Values to post to add credit to a specific child account

	*/
	AddCredits *models.AddCredits
	/*ChildID
	  id of reseller's child

	*/
	ChildID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the add credits params
func (o *AddCreditsParams) WithTimeout(timeout time.Duration) *AddCreditsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add credits params
func (o *AddCreditsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add credits params
func (o *AddCreditsParams) WithContext(ctx context.Context) *AddCreditsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add credits params
func (o *AddCreditsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add credits params
func (o *AddCreditsParams) WithHTTPClient(client *http.Client) *AddCreditsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add credits params
func (o *AddCreditsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAddCredits adds the addCredits to the add credits params
func (o *AddCreditsParams) WithAddCredits(addCredits *models.AddCredits) *AddCreditsParams {
	o.SetAddCredits(addCredits)
	return o
}

// SetAddCredits adds the addCredits to the add credits params
func (o *AddCreditsParams) SetAddCredits(addCredits *models.AddCredits) {
	o.AddCredits = addCredits
}

// WithChildID adds the childID to the add credits params
func (o *AddCreditsParams) WithChildID(childID int64) *AddCreditsParams {
	o.SetChildID(childID)
	return o
}

// SetChildID adds the childId to the add credits params
func (o *AddCreditsParams) SetChildID(childID int64) {
	o.ChildID = childID
}

// WriteToRequest writes these params to a swagger request
func (o *AddCreditsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.AddCredits == nil {
		o.AddCredits = new(models.AddCredits)
	}

	if err := r.SetBodyParam(o.AddCredits); err != nil {
		return err
	}

	// path param childId
	if err := r.SetPathParam("childId", swag.FormatInt64(o.ChildID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
