// Code generated by go-swagger; DO NOT EDIT.

package reseller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"APIv3_go_wrapper/models"
)

// NewUpdateResellerChildParams creates a new UpdateResellerChildParams object
// with the default values initialized.
func NewUpdateResellerChildParams() *UpdateResellerChildParams {
	var ()
	return &UpdateResellerChildParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateResellerChildParamsWithTimeout creates a new UpdateResellerChildParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateResellerChildParamsWithTimeout(timeout time.Duration) *UpdateResellerChildParams {
	var ()
	return &UpdateResellerChildParams{

		timeout: timeout,
	}
}

// NewUpdateResellerChildParamsWithContext creates a new UpdateResellerChildParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateResellerChildParamsWithContext(ctx context.Context) *UpdateResellerChildParams {
	var ()
	return &UpdateResellerChildParams{

		Context: ctx,
	}
}

// NewUpdateResellerChildParamsWithHTTPClient creates a new UpdateResellerChildParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateResellerChildParamsWithHTTPClient(client *http.Client) *UpdateResellerChildParams {
	var ()
	return &UpdateResellerChildParams{
		HTTPClient: client,
	}
}

/*UpdateResellerChildParams contains all the parameters to send to the API endpoint
for the update reseller child operation typically these are written to a http.Request
*/
type UpdateResellerChildParams struct {

	/*ChildAuthKey
	  auth key of reseller's child

	*/
	ChildAuthKey string
	/*ResellerChild
	  values to update in child profile

	*/
	ResellerChild *models.UpdateChild

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update reseller child params
func (o *UpdateResellerChildParams) WithTimeout(timeout time.Duration) *UpdateResellerChildParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update reseller child params
func (o *UpdateResellerChildParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update reseller child params
func (o *UpdateResellerChildParams) WithContext(ctx context.Context) *UpdateResellerChildParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update reseller child params
func (o *UpdateResellerChildParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update reseller child params
func (o *UpdateResellerChildParams) WithHTTPClient(client *http.Client) *UpdateResellerChildParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update reseller child params
func (o *UpdateResellerChildParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithChildAuthKey adds the childAuthKey to the update reseller child params
func (o *UpdateResellerChildParams) WithChildAuthKey(childAuthKey string) *UpdateResellerChildParams {
	o.SetChildAuthKey(childAuthKey)
	return o
}

// SetChildAuthKey adds the childAuthKey to the update reseller child params
func (o *UpdateResellerChildParams) SetChildAuthKey(childAuthKey string) {
	o.ChildAuthKey = childAuthKey
}

// WithResellerChild adds the resellerChild to the update reseller child params
func (o *UpdateResellerChildParams) WithResellerChild(resellerChild *models.UpdateChild) *UpdateResellerChildParams {
	o.SetResellerChild(resellerChild)
	return o
}

// SetResellerChild adds the resellerChild to the update reseller child params
func (o *UpdateResellerChildParams) SetResellerChild(resellerChild *models.UpdateChild) {
	o.ResellerChild = resellerChild
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateResellerChildParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param childAuthKey
	if err := r.SetPathParam("childAuthKey", o.ChildAuthKey); err != nil {
		return err
	}

	if o.ResellerChild != nil {
		if err := r.SetBodyParam(o.ResellerChild); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
