/*
 * SendinBlue API
 *
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@sendinblue.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package sibapiv3

type SendReportEmail struct {

	// Subject of the email message
	Subject string `json:"subject,omitempty"`

	// Email addresses of the recipients
	To []string `json:"to,omitempty"`

	// Type of the message body
	ContentType string `json:"contentType,omitempty"`

	// Email addresses of the recipients in bcc
	Bcc []string `json:"bcc,omitempty"`

	// Email addresses of the recipients in cc
	Cc []string `json:"cc,omitempty"`

	// Body of the email message
	Body string `json:"body,omitempty"`
}
