// Code generated by go-swagger; DO NOT EDIT.

package s_m_s_campaigns

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/sendinblue/APIv3-go-library/models"
)

// CreateSmsCampaignReader is a Reader for the CreateSmsCampaign structure.
type CreateSmsCampaignReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateSmsCampaignReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateSmsCampaignCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateSmsCampaignBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateSmsCampaignCreated creates a CreateSmsCampaignCreated with default headers values
func NewCreateSmsCampaignCreated() *CreateSmsCampaignCreated {
	return &CreateSmsCampaignCreated{}
}

/*CreateSmsCampaignCreated handles this case with default header values.

SMS campaign created
*/
type CreateSmsCampaignCreated struct {
	Payload *models.CreateModel
}

func (o *CreateSmsCampaignCreated) Error() string {
	return fmt.Sprintf("[POST /smsCampaigns][%d] createSmsCampaignCreated  %+v", 201, o.Payload)
}

func (o *CreateSmsCampaignCreated) GetPayload() *models.CreateModel {
	return o.Payload
}

func (o *CreateSmsCampaignCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreateModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateSmsCampaignBadRequest creates a CreateSmsCampaignBadRequest with default headers values
func NewCreateSmsCampaignBadRequest() *CreateSmsCampaignBadRequest {
	return &CreateSmsCampaignBadRequest{}
}

/*CreateSmsCampaignBadRequest handles this case with default header values.

bad request
*/
type CreateSmsCampaignBadRequest struct {
	Payload *models.ErrorModel
}

func (o *CreateSmsCampaignBadRequest) Error() string {
	return fmt.Sprintf("[POST /smsCampaigns][%d] createSmsCampaignBadRequest  %+v", 400, o.Payload)
}

func (o *CreateSmsCampaignBadRequest) GetPayload() *models.ErrorModel {
	return o.Payload
}

func (o *CreateSmsCampaignBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
