// Code generated by go-swagger; DO NOT EDIT.

package s_m_s_campaigns

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"APIv3_go_wrapper/models"
)

// NewCreateSmsCampaignParams creates a new CreateSmsCampaignParams object
// with the default values initialized.
func NewCreateSmsCampaignParams() *CreateSmsCampaignParams {
	var ()
	return &CreateSmsCampaignParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateSmsCampaignParamsWithTimeout creates a new CreateSmsCampaignParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateSmsCampaignParamsWithTimeout(timeout time.Duration) *CreateSmsCampaignParams {
	var ()
	return &CreateSmsCampaignParams{

		timeout: timeout,
	}
}

// NewCreateSmsCampaignParamsWithContext creates a new CreateSmsCampaignParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateSmsCampaignParamsWithContext(ctx context.Context) *CreateSmsCampaignParams {
	var ()
	return &CreateSmsCampaignParams{

		Context: ctx,
	}
}

// NewCreateSmsCampaignParamsWithHTTPClient creates a new CreateSmsCampaignParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateSmsCampaignParamsWithHTTPClient(client *http.Client) *CreateSmsCampaignParams {
	var ()
	return &CreateSmsCampaignParams{
		HTTPClient: client,
	}
}

/*CreateSmsCampaignParams contains all the parameters to send to the API endpoint
for the create sms campaign operation typically these are written to a http.Request
*/
type CreateSmsCampaignParams struct {

	/*CreateSmsCampaign
	  Values to create an SMS Campaign

	*/
	CreateSmsCampaign *models.CreateSmsCampaign

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create sms campaign params
func (o *CreateSmsCampaignParams) WithTimeout(timeout time.Duration) *CreateSmsCampaignParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create sms campaign params
func (o *CreateSmsCampaignParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create sms campaign params
func (o *CreateSmsCampaignParams) WithContext(ctx context.Context) *CreateSmsCampaignParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create sms campaign params
func (o *CreateSmsCampaignParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create sms campaign params
func (o *CreateSmsCampaignParams) WithHTTPClient(client *http.Client) *CreateSmsCampaignParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create sms campaign params
func (o *CreateSmsCampaignParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCreateSmsCampaign adds the createSmsCampaign to the create sms campaign params
func (o *CreateSmsCampaignParams) WithCreateSmsCampaign(createSmsCampaign *models.CreateSmsCampaign) *CreateSmsCampaignParams {
	o.SetCreateSmsCampaign(createSmsCampaign)
	return o
}

// SetCreateSmsCampaign adds the createSmsCampaign to the create sms campaign params
func (o *CreateSmsCampaignParams) SetCreateSmsCampaign(createSmsCampaign *models.CreateSmsCampaign) {
	o.CreateSmsCampaign = createSmsCampaign
}

// WriteToRequest writes these params to a swagger request
func (o *CreateSmsCampaignParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.CreateSmsCampaign != nil {
		if err := r.SetBodyParam(o.CreateSmsCampaign); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
