// Code generated by go-swagger; DO NOT EDIT.

package s_m_s_campaigns

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/sendinblue/APIv3-go-library/models"
)

// NewRequestSmsRecipientExportParams creates a new RequestSmsRecipientExportParams object
// with the default values initialized.
func NewRequestSmsRecipientExportParams() *RequestSmsRecipientExportParams {
	var ()
	return &RequestSmsRecipientExportParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRequestSmsRecipientExportParamsWithTimeout creates a new RequestSmsRecipientExportParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRequestSmsRecipientExportParamsWithTimeout(timeout time.Duration) *RequestSmsRecipientExportParams {
	var ()
	return &RequestSmsRecipientExportParams{

		timeout: timeout,
	}
}

// NewRequestSmsRecipientExportParamsWithContext creates a new RequestSmsRecipientExportParams object
// with the default values initialized, and the ability to set a context for a request
func NewRequestSmsRecipientExportParamsWithContext(ctx context.Context) *RequestSmsRecipientExportParams {
	var ()
	return &RequestSmsRecipientExportParams{

		Context: ctx,
	}
}

// NewRequestSmsRecipientExportParamsWithHTTPClient creates a new RequestSmsRecipientExportParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRequestSmsRecipientExportParamsWithHTTPClient(client *http.Client) *RequestSmsRecipientExportParams {
	var ()
	return &RequestSmsRecipientExportParams{
		HTTPClient: client,
	}
}

/*RequestSmsRecipientExportParams contains all the parameters to send to the API endpoint
for the request sms recipient export operation typically these are written to a http.Request
*/
type RequestSmsRecipientExportParams struct {

	/*CampaignID
	  id of the campaign

	*/
	CampaignID int64
	/*RecipientExport
	  Values to send for a recipient export request

	*/
	RecipientExport *models.RequestSmsRecipientExport

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the request sms recipient export params
func (o *RequestSmsRecipientExportParams) WithTimeout(timeout time.Duration) *RequestSmsRecipientExportParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the request sms recipient export params
func (o *RequestSmsRecipientExportParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the request sms recipient export params
func (o *RequestSmsRecipientExportParams) WithContext(ctx context.Context) *RequestSmsRecipientExportParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the request sms recipient export params
func (o *RequestSmsRecipientExportParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the request sms recipient export params
func (o *RequestSmsRecipientExportParams) WithHTTPClient(client *http.Client) *RequestSmsRecipientExportParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the request sms recipient export params
func (o *RequestSmsRecipientExportParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCampaignID adds the campaignID to the request sms recipient export params
func (o *RequestSmsRecipientExportParams) WithCampaignID(campaignID int64) *RequestSmsRecipientExportParams {
	o.SetCampaignID(campaignID)
	return o
}

// SetCampaignID adds the campaignId to the request sms recipient export params
func (o *RequestSmsRecipientExportParams) SetCampaignID(campaignID int64) {
	o.CampaignID = campaignID
}

// WithRecipientExport adds the recipientExport to the request sms recipient export params
func (o *RequestSmsRecipientExportParams) WithRecipientExport(recipientExport *models.RequestSmsRecipientExport) *RequestSmsRecipientExportParams {
	o.SetRecipientExport(recipientExport)
	return o
}

// SetRecipientExport adds the recipientExport to the request sms recipient export params
func (o *RequestSmsRecipientExportParams) SetRecipientExport(recipientExport *models.RequestSmsRecipientExport) {
	o.RecipientExport = recipientExport
}

// WriteToRequest writes these params to a swagger request
func (o *RequestSmsRecipientExportParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param campaignId
	if err := r.SetPathParam("campaignId", swag.FormatInt64(o.CampaignID)); err != nil {
		return err
	}

	if o.RecipientExport != nil {
		if err := r.SetBodyParam(o.RecipientExport); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
