// Code generated by go-swagger; DO NOT EDIT.

package s_m_s_campaigns

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/sendinblue/APIv3-go-library/models"
)

// UpdateSMSCampaignStatusReader is a Reader for the UpdateSMSCampaignStatus structure.
type UpdateSMSCampaignStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateSMSCampaignStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewUpdateSMSCampaignStatusNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewUpdateSMSCampaignStatusBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewUpdateSMSCampaignStatusNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateSMSCampaignStatusNoContent creates a UpdateSMSCampaignStatusNoContent with default headers values
func NewUpdateSMSCampaignStatusNoContent() *UpdateSMSCampaignStatusNoContent {
	return &UpdateSMSCampaignStatusNoContent{}
}

/*UpdateSMSCampaignStatusNoContent handles this case with default header values.

The campaign status has been updated successfully
*/
type UpdateSMSCampaignStatusNoContent struct {
}

func (o *UpdateSMSCampaignStatusNoContent) Error() string {
	return fmt.Sprintf("[PUT /smsCampaigns/{campaignId}/status][%d] updateSMSCampaignStatusNoContent ", 204)
}

func (o *UpdateSMSCampaignStatusNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateSMSCampaignStatusBadRequest creates a UpdateSMSCampaignStatusBadRequest with default headers values
func NewUpdateSMSCampaignStatusBadRequest() *UpdateSMSCampaignStatusBadRequest {
	return &UpdateSMSCampaignStatusBadRequest{}
}

/*UpdateSMSCampaignStatusBadRequest handles this case with default header values.

bad request
*/
type UpdateSMSCampaignStatusBadRequest struct {
	Payload *models.ErrorModel
}

func (o *UpdateSMSCampaignStatusBadRequest) Error() string {
	return fmt.Sprintf("[PUT /smsCampaigns/{campaignId}/status][%d] updateSMSCampaignStatusBadRequest  %+v", 400, o.Payload)
}

func (o *UpdateSMSCampaignStatusBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateSMSCampaignStatusNotFound creates a UpdateSMSCampaignStatusNotFound with default headers values
func NewUpdateSMSCampaignStatusNotFound() *UpdateSMSCampaignStatusNotFound {
	return &UpdateSMSCampaignStatusNotFound{}
}

/*UpdateSMSCampaignStatusNotFound handles this case with default header values.

Campaign ID not found
*/
type UpdateSMSCampaignStatusNotFound struct {
	Payload *models.ErrorModel
}

func (o *UpdateSMSCampaignStatusNotFound) Error() string {
	return fmt.Sprintf("[PUT /smsCampaigns/{campaignId}/status][%d] updateSMSCampaignStatusNotFound  %+v", 404, o.Payload)
}

func (o *UpdateSMSCampaignStatusNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
