// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateSenderModel create sender model
// swagger:model createSenderModel

type CreateSenderModel struct {

	// Status of DKIM configuration for the sender (true = DKIM not well configured, false = DKIM well configured)
	DkimError bool `json:"dkimError,omitempty"`

	// ID of the Sender created
	// Required: true
	ID *int64 `json:"id"`

	// Status of SPF configuration for the sender (true = SPF not well configured, false = SPF well configured)
	SpfError bool `json:"spfError,omitempty"`
}

/* polymorph createSenderModel dkimError false */

/* polymorph createSenderModel id false */

/* polymorph createSenderModel spfError false */

// Validate validates this create sender model
func (m *CreateSenderModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateID(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateSenderModel) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CreateSenderModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateSenderModel) UnmarshalBinary(b []byte) error {
	var res CreateSenderModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
