// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetIPFromSender get Ip from sender
// swagger:model getIpFromSender

type GetIPFromSender struct {

	// Domain associated to the IP
	// Required: true
	Domain *string `json:"domain"`

	// ID of the dedicated IP
	// Required: true
	ID *int64 `json:"id"`

	// Dedicated IP
	// Required: true
	IP *string `json:"ip"`

	// Weight of the IP
	// Required: true
	Weight *int64 `json:"weight"`
}

/* polymorph getIpFromSender domain false */

/* polymorph getIpFromSender id false */

/* polymorph getIpFromSender ip false */

/* polymorph getIpFromSender weight false */

// Validate validates this get Ip from sender
func (m *GetIPFromSender) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDomain(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateIP(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateWeight(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetIPFromSender) validateDomain(formats strfmt.Registry) error {

	if err := validate.Required("domain", "body", m.Domain); err != nil {
		return err
	}

	return nil
}

func (m *GetIPFromSender) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *GetIPFromSender) validateIP(formats strfmt.Registry) error {

	if err := validate.Required("ip", "body", m.IP); err != nil {
		return err
	}

	return nil
}

func (m *GetIPFromSender) validateWeight(formats strfmt.Registry) error {

	if err := validate.Required("weight", "body", m.Weight); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetIPFromSender) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetIPFromSender) UnmarshalBinary(b []byte) error {
	var res GetIPFromSender
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
