// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetList get list
// swagger:model getList

type GetList struct {

	// ID of the list
	// Required: true
	ID *int64 `json:"id"`

	// Name of the list
	// Required: true
	Name *string `json:"name"`

	// Number of blacklisted contacts in the list
	// Required: true
	TotalBlacklisted *int64 `json:"totalBlacklisted"`

	// Number of contacts in the list
	// Required: true
	TotalSubscribers *int64 `json:"totalSubscribers"`
}

/* polymorph getList id false */

/* polymorph getList name false */

/* polymorph getList totalBlacklisted false */

/* polymorph getList totalSubscribers false */

// Validate validates this get list
func (m *GetList) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateID(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateTotalBlacklisted(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateTotalSubscribers(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetList) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *GetList) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *GetList) validateTotalBlacklisted(formats strfmt.Registry) error {

	if err := validate.Required("totalBlacklisted", "body", m.TotalBlacklisted); err != nil {
		return err
	}

	return nil
}

func (m *GetList) validateTotalSubscribers(formats strfmt.Registry) error {

	if err := validate.Required("totalSubscribers", "body", m.TotalSubscribers); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetList) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetList) UnmarshalBinary(b []byte) error {
	var res GetList
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
